apiVersion: v1
kind: Service
metadata:
  name: petclinic-frontend
  labels:
    app: petclinic
    tier: frontend
    thing: petclinic-frontend-svc-metadata
spec:
  ports:
  - port: 8080
  selector:
    app: petclinic
    tier: frontend
