apiVersion: v1
kind: ReplicationController
metadata:
  name: petclinic-backend
  labels:
    app: petclinic
    tier: backend
    thing: petclinic-backend-rc-metadata
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic
        tier: backend
        thing: petclinic-backend-template-metadata
    spec:
      containers:
      - name: petclinic-backend
        image: 192.168.99.101:5000/petportal/petclinic-backend:1.1-20152112140630
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
