apiVersion: v1
kind: ReplicationController
metadata:
  name: petclinic-frontend2
  labels:
    app: petclinic
    tier: frontend
    thing: petclinic-frontend-rc-metadata
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: petclinic
        tier: frontend
        thing: petclinic-frontend-rc-template-metadata
    spec:
      containers:
      - name: petclinic-frontend
        image: 192.168.99.101:5000/petportal/petclinic:3.1-20152112140630
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
